
<small>
Why You use Numpy over lists ?

- Lists are slow and meanwhile numpy are very fast.
- Numpy Arrays are faster because of Fixed Type.
- We can specify the size of numpy objects
- No Type checking in numpy as it store homogenous elements
- Numpy array uses contiguous Memory, because of this it has Single Instructions Multiple daata vector processing, Effective cache utilization.


Applications of Numpy

- Mathematics
- Plotting
- Backend (Pandas, Connect 4, Digital Photography)
- Maching Learning

</small>


In [1]:
import numpy as np

In [3]:
a  = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([[9.0,8.0,7.0], [1.0, 2.1, 3.5]])
b

array([[9. , 8. , 7. ],
       [1. , 2.1, 3.5]])

In [6]:
a.ndim

1

In [7]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int32')

In [10]:
b.itemsize

8

In [12]:

b.size

6

In [13]:
b.itemsize

8

In [14]:
a , b

(array([1, 2, 3]),
 array([[9. , 8. , 7. ],
        [1. , 2.1, 3.5]]))

In [16]:
b.dtype

dtype('float64')

In [18]:
b.dtype

dtype('float64')

In [23]:
b =b.astype('float32')


In [24]:
b.dtype

dtype('float32')

In [29]:
# Accessing/ Changing Specific elements, rows , columns etc

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [30]:
a.shape

(2, 7)

In [31]:
a[1,5]

13

In [35]:
a[1, 0:2]

array([8, 9])

In [37]:
a[1,0:2]= np.array([7,7])

In [38]:
a


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 7,  7, 10, 11, 12, 13, 14]])

In [39]:
# Initializing different arrays

np.zeros(5)


array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
# Any other number

np.full((2,2), 100, dtype = 'float32')

array([[100., 100.],
       [100., 100.]], dtype=float32)

In [45]:
# Any other number (full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
# Random decimal Number

np.random.rand(4,1)*100

array([[81.84279038],
       [23.40464634],
       [64.49167922],
       [43.57557854]])

In [52]:
# Random Integer values
np.random.randint(4,12, size=(3,3))
# 12 is exclusive

array([[ 7,  8,  5],
       [10,  8,  9],
       [11,  9,  9]])

In [53]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
arr = np.array([[1,2,3]])
repeater = np.repeat(arr,3,axis =0)
repeater

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [68]:
# Initialize Array Problem

arr = np.ones((5,5))
arr[1:-1, 1:-1] = np.zeros((3,3))
arr[2,2]= 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
# Copying Arrays Warning

# Be careful when copying !!

a = np.array([1,2,3])
b = a

b[0] =100
a ,b

(array([100,   2,   3]), array([100,   2,   3]))

In [73]:
a = np.array([1,2,3])
c = a.copy()

c[0]=100

a, c

(array([1, 2, 3]), array([100,   2,   3]))

In [74]:
# Mathematics

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [75]:
a+2

array([3, 4, 5, 6])

In [76]:
a-2

array([-1,  0,  1,  2])

In [77]:
a*2

array([2, 4, 6, 8])

In [78]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [79]:
a+=2

In [80]:
a

array([3, 4, 5, 6])

In [81]:
b = np.array([1,1,1,1])
a+b

array([4, 5, 6, 7])

In [82]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [83]:
# Take the sin

np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [84]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [86]:
# Linear Algebra

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [87]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [90]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1)
b

array([ 5, 10])

In [92]:
c = np.max(a, axis=0)
c

array([ 6,  7,  8,  9, 10])

In [93]:
np.max(a)

10

In [95]:
np.sum(a)

55

In [96]:
# Reorganizing Arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [97]:
# Vertically Stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
# Horizonal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [99]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [103]:
# Loading Data and Advanced Indexing

filedata = np.genfromtxt('../data/numpydata.txt', delimiter=',')

In [104]:
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [12., 14., 45., 67., 34., 12., 15., 12., 67.],
       [74., 13., 32., 36., 46., 88., 45., 86., 10.]])

In [106]:
filedata.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [12, 14, 45, 67, 34, 12, 15, 12, 67],
       [74, 13, 32, 36, 46, 88, 45, 86, 10]])

In [107]:
# Advance Indexing and Boolean Masking

filedata>50


array([[False, False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False,  True],
       [ True, False, False, False, False,  True, False,  True, False]])

In [109]:
filedata[filedata>50].astype('int32')

array([67, 67, 74, 88, 86])

In [111]:
output = np.any(filedata < 50)
print(output)

True


In [112]:
output = np.all(filedata < 50, axis=1)
print(output)


[ True False False]


In [115]:
filedata[(filedata>50) & (filedata<70)].astype('int32')

array([67, 67])

In [120]:
filedata, filedata[[0,1,2],[0,1,2]].astype('int32')

(array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12., 14., 45., 67., 34., 12., 15., 12., 67.],
        [74., 13., 32., 36., 46., 88., 45., 86., 10.]]),
 array([ 1, 14, 32]))

In [121]:
filedata , filedata [[0,2],-3:]

(array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [12., 14., 45., 67., 34., 12., 15., 12., 67.],
        [74., 13., 32., 36., 46., 88., 45., 86., 10.]]),
 array([[ 7.,  8.,  9.],
        [45., 86., 10.]]))

In [122]:
filedata = filedata.astype('int32')